import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import ReduxProvider from "@/components/redux-provider"; 

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "WeatherPulse",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    
      <html lang="en">
        <body
          className={`${inter.className} h-full bg-black m-auto max-w-[72rem]`}
        >
          <ReduxProvider>{children}</ReduxProvider>
        </body>
      </html>
    
  );
}
